antiAffinity: preferred
topologyKey: kubernetes.io/hostname

hostname: rancher.my.org

ingress:
  enabled: false

service:
  type: "LoadBalancer"
  annotations: {}

replicas: 3

resources:
#  limits:
#    cpu: "2"
#    memory: 8Gi
#  requests:
#    cpu: "2"
#    memory: 8Gi
